/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mypackage;

import classes.Mysqlconnection;
import classes.User;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class AdministratorForm extends javax.swing.JFrame {
    User currentUser;
    Mysqlconnection connect;

    /**
     * Creates new form AdministratorForm
     */
    public AdministratorForm() {
        currentUser=new User();
        this.connect = new Mysqlconnection();
        initComponents();
    }
    
    public AdministratorForm(String userid, String accesstype) {
        this.connect = new Mysqlconnection();
        currentUser=new User();
        currentUser.setUserID(userid);
        currentUser.setAccess_Type(accesstype);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Studentnumber_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Student_table = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        student_curriculum_table = new javax.swing.JTable();
        get_student_details_button = new javax.swing.JButton();
        student_risk_field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        students_credits_field = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        student_name_field = new javax.swing.JTextField();
        student_surname_field = new javax.swing.JTextField();
        student_degree_field = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        view_lecturer_field = new javax.swing.JTextField();
        view_lecturer_button = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        lecturer_name_field = new javax.swing.JTextField();
        lecturer_surname_field = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lecturer_modules_field = new javax.swing.JTextField();
        student_risk_field1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        new_student_number_field = new javax.swing.JTextField();
        new_student_name_field = new javax.swing.JTextField();
        new_student_surname_field = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        new_credits_field = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        add_student_button = new javax.swing.JButton();
        remove_student_button = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        remove_student_number_field = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        Degree_combo_box = new javax.swing.JComboBox<>();
        yos_combo_box = new javax.swing.JComboBox<>();
        sos_combo_box = new javax.swing.JComboBox<>();
        term_condition_combo_box = new javax.swing.JComboBox<>();
        years_registered_combo_box = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(204, 0, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Student Number");

        Studentnumber_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Studentnumber_fieldActionPerformed(evt);
            }
        });

        Student_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Module", "Mark", "Semester taken", "Year taken", "Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Student_table);
        if (Student_table.getColumnModel().getColumnCount() > 0) {
            Student_table.getColumnModel().getColumn(2).setHeaderValue("Semester taken");
            Student_table.getColumnModel().getColumn(3).setHeaderValue("Year taken");
            Student_table.getColumnModel().getColumn(4).setHeaderValue("Rating");
        }

        student_curriculum_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Module", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(student_curriculum_table);

        get_student_details_button.setText("Get Details");
        get_student_details_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_student_details_buttonActionPerformed(evt);
            }
        });

        student_risk_field.setEditable(false);

        jLabel12.setText("Term Condition");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("Current Curriculum");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Student's Past");

        jLabel15.setText("Total Credits Achieved");

        students_credits_field.setEditable(false);
        students_credits_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                students_credits_fieldActionPerformed(evt);
            }
        });

        jLabel16.setText("Degree");

        jLabel17.setText("Surname");

        jLabel18.setText("Name");

        student_name_field.setEditable(false);

        student_surname_field.setEditable(false);

        student_degree_field.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(35, 35, 35)
                                .addComponent(students_credits_field, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Studentnumber_field, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(student_risk_field)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(109, 109, 109)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(student_degree_field)
                                    .addComponent(student_name_field)
                                    .addComponent(student_surname_field))))
                        .addGap(278, 278, 278)
                        .addComponent(get_student_details_button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Studentnumber_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get_student_details_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(student_name_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(student_surname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(student_degree_field, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(student_risk_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(students_credits_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("View Student", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 51, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Lecturer ID");

        view_lecturer_button.setText("Get Details");
        view_lecturer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_lecturer_buttonActionPerformed(evt);
            }
        });

        jLabel19.setText("Name");

        lecturer_name_field.setEditable(false);

        lecturer_surname_field.setEditable(false);

        jLabel20.setText("Surname");

        jLabel21.setText("Modules");

        lecturer_modules_field.setEditable(false);

        student_risk_field1.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(student_risk_field1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lecturer_modules_field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lecturer_surname_field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lecturer_name_field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(view_lecturer_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(view_lecturer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_lecturer_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_lecturer_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lecturer_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lecturer_surname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lecturer_modules_field, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(27, 27, 27)
                .addComponent(student_risk_field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Lecturer", jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 102, 255));

        jLabel22.setText("Student Number");

        jLabel23.setText("Name");

        jLabel24.setText("Surname");

        jLabel25.setText("Degree");

        jLabel26.setText("Years registered");

        jLabel27.setText("Year of Study");

        jLabel28.setText("Semester of Study");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel29.setText("New Student's Details");

        jLabel30.setText("Credits");

        jLabel31.setText("Term Condition");

        add_student_button.setText("Add Student");
        add_student_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_student_buttonActionPerformed(evt);
            }
        });

        remove_student_button.setText("Remove Student");
        remove_student_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_student_buttonActionPerformed(evt);
            }
        });

        jLabel32.setText("Student Number");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel33.setText("Remove Student ");

        Degree_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-not selected-", "agricultural engineering", "chemical engineering", "civil engineering", "computer engineering", "electrical engineering", "electronic engineering", "mechanical engineering" }));
        Degree_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Degree_combo_boxActionPerformed(evt);
            }
        });

        yos_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-not selected-", "1", "2", "3", "4" }));

        sos_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-not selected-", "1", "2" }));

        term_condition_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-not selected", "green", "orange ", "red" }));
        term_condition_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                term_condition_combo_boxActionPerformed(evt);
            }
        });

        years_registered_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-not selected-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(add_student_button)
                        .addGap(546, 546, 546))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yos_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(new_student_number_field)
                                    .addComponent(new_student_name_field)
                                    .addComponent(new_student_surname_field)
                                    .addComponent(Degree_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sos_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel29)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(new_credits_field, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(term_condition_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(years_registered_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(remove_student_number_field, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGap(140, 140, 140)
                                            .addComponent(remove_student_button)))
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(511, 511, 511))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(new_student_number_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(new_student_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(new_student_surname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Degree_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(yos_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sos_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(term_condition_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_credits_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(years_registered_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_student_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(remove_student_number_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(remove_student_button)
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Add/Remove Student", jPanel6);

        jButton10.setText("Logout");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

         if(JOptionPane.showConfirmDialog(this, "Are you sure that you want to logout?", "Confirmation", JOptionPane.YES_NO_OPTION)==0){        //confirm if the user wants to logout
            new LoginForm().setVisible(true);
            this.dispose();
         }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void view_lecturer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_lecturer_buttonActionPerformed
        try {
            if(view_lecturer_field.getText().isEmpty()){        
                JOptionPane.showMessageDialog(this, "Please enter the lecturer's id number", "Empty Field", JOptionPane.ERROR_MESSAGE);         //if the lecturer's id is invalid, display an error messaage
            }
            else if(connect.checkuserdb("Lecturer", "id", view_lecturer_field.getText())==false){
                JOptionPane.showMessageDialog(this, "This lecturer is not on the system", "Invalid ID Number", JOptionPane.ERROR_MESSAGE);      //show lecturer's details if the id is valid
            }
            else{
                String name="";         //intialize lecturer details
                String surname="";
                String modules="";
                name=connect.getspecificdata("Lecturer", "id", view_lecturer_field.getText(), "Name");
                surname=connect.getspecificdata("Lecturer", "id",  view_lecturer_field.getText(), "Surname");
                modules=connect.getspecificdata("Lecturer", "id",  view_lecturer_field.getText(), "Modules");
                lecturer_name_field.setText(name);
                lecturer_surname_field.setText(surname);
                lecturer_modules_field.setText(modules);

            }
        }
        catch (Exception ex) {
            Logger.getLogger(StudentHomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_view_lecturer_buttonActionPerformed

    private void students_credits_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_students_credits_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_students_credits_fieldActionPerformed

    private void get_student_details_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_student_details_buttonActionPerformed
        try {
            if(Studentnumber_field.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter the student's student number", "Empty Field", JOptionPane.ERROR_MESSAGE);             //display an error if field is empty
            }
            else if(connect.checkuserdb("Student", "id", Studentnumber_field.getText())==false){
                JOptionPane.showMessageDialog(this, "This student number is not on the system", "Invalid Student Number", JOptionPane.ERROR_MESSAGE);   //display an error id studdent number is invalid  
            }
            else{

                String term_condition="";
                String credits="";
                String name="";
                String surname="";
                String degree="";
                connect.setuptable(this.Student_table, "modules.`students past`", "Module,Mark,`Semester taken`,`Year taken`,Rating", "`Student Number`", Studentnumber_field.getText());   //if details are correct show the student's past
                connect.setuptable(this.student_curriculum_table, "modules.`current curriculum`", "Module,Credits", "id", Studentnumber_field.getText());
                term_condition = connect.getspecificdata("Student", "id", Studentnumber_field.getText(), "Term Condition");
                credits=connect.getspecificdata("Student", "id", Studentnumber_field.getText(), "Credits");
                name=connect.getspecificdata("Student", "id", Studentnumber_field.getText(), "Student Name");
                surname=connect.getspecificdata("Student", "id", Studentnumber_field.getText(), "Surname");
                degree=connect.getspecificdata("Student", "id", Studentnumber_field.getText(), "Degree");
                student_risk_field.setText(term_condition);
                students_credits_field.setText(credits);
                student_name_field.setText(name);
                student_surname_field.setText(surname);
                student_degree_field.setText(degree);
                if(connect.checkuserdb("modules.`current curriculum`", "id" , currentUser.getUserID())){
                connect.setuptable(student_curriculum_table, "modules.`current curriculum`", "`Module`,Credits", "id", currentUser.getUserID());        //show the student's current curriculum
                }

            }
        }
        catch (Exception ex) {
            Logger.getLogger(StudentHomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_get_student_details_buttonActionPerformed

    private void Studentnumber_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Studentnumber_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Studentnumber_fieldActionPerformed

    private void add_student_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_student_buttonActionPerformed
        try {
            String student_number="";
            String name="";
            String surname="";
            String degree="";
            String yos="";
            String sos="";
            String term_condition="";
            String credits="";
            String year_reg="";
            String password="";
            if(new_student_number_field.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter a student number", "Empty Field", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else if(connect.checkuserdb("Student", "id", new_student_number_field.getText())){
                JOptionPane.showMessageDialog(this, "This student number is already on the system", "Student number is taken", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                student_number=new_student_number_field.getText();
            }
            if(new_student_name_field.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter the student's name", "Empty Field", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                name=new_student_name_field.getText();
            }
            if(new_student_surname_field.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter the student's surname", "Empty Field", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                surname=new_student_surname_field.getText();
            }
            if(Degree_combo_box.getSelectedItem().toString().equals("-not selected-")){
                JOptionPane.showMessageDialog(this, "Please select the student's degree", "Empty Field", JOptionPane.ERROR_MESSAGE);/////////////////////
                return;
            }
            else{
                degree=Degree_combo_box.getSelectedItem().toString();
            }
            if(yos_combo_box.getSelectedItem().toString().equals("-not selected-")){
                JOptionPane.showMessageDialog(this, "Please select the student's year of study", "Empty Field", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                yos=yos_combo_box.getSelectedItem().toString();
            }
            if(sos_combo_box.getSelectedItem().toString().equals("-not selected-")){
                JOptionPane.showMessageDialog(this, "Please select the semester of study", "Empty Field", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                sos=sos_combo_box.getSelectedItem().toString();
            }
            if(term_condition_combo_box.getSelectedItem().toString().equals("-not selected-")){
                JOptionPane.showMessageDialog(this, "Please select the student's risk status", "Empty Field", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                term_condition=term_condition_combo_box.getSelectedItem().toString();
            }
            if(new_credits_field.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter the student's credits", "Empty Field", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                credits=new_credits_field.getText();
            }
            if(years_registered_combo_box.getSelectedItem().toString().equals("-not selected-")){
                JOptionPane.showMessageDialog(this, "Please enter the how long the student has been registered for", "Empty Field", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                year_reg=years_registered_combo_box.getSelectedItem().toString();
            }
            if(JOptionPane.showConfirmDialog(this, "Are you sure that you want to add this student?", "Confirmation", JOptionPane.YES_NO_OPTION)==0){
                String query_values="'"+student_number+"','"+name+"','"+surname+"','"+degree+"','"+yos+"','"+sos+"','"+term_condition+"','"+credits+"','"+year_reg+"','"+student_number+"'";
                connect.addtodb("Student", query_values);
                new_student_number_field.removeAll();
                new_student_name_field.removeAll();
                new_student_surname_field.removeAll();
                new_credits_field.removeAll();
                JOptionPane.showMessageDialog(this, "Student has been added", "Student added", JOptionPane.INFORMATION_MESSAGE);
            }

        }

        catch (Exception ex) {
            Logger.getLogger(StudentHomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_student_buttonActionPerformed

    private void remove_student_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_student_buttonActionPerformed
        String remove_student_number=remove_student_number_field.getText();
        if(remove_student_number_field.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a Student number", "Empty Field", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            try{
                if(connect.checkuserdb("Student", "id", remove_student_number)){
                    if(JOptionPane.showConfirmDialog(this, "Are you sure that you want to remove this student?", "Confirmation", JOptionPane.YES_NO_OPTION)==0){
                        connect.deletefromdb("Student", "id", remove_student_number);
                        JOptionPane.showMessageDialog(this, "Student("+remove_student_number+")"+"has been removed from the system.", "Student removed", JOptionPane.INFORMATION_MESSAGE );
                        remove_student_number_field.removeAll();

                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "This student does not exist on the system", "Invalid student number", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            catch (Exception ex) {
                Logger.getLogger(StudentHomeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_remove_student_buttonActionPerformed

    private void Degree_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Degree_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Degree_combo_boxActionPerformed

    private void term_condition_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_term_condition_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_term_condition_combo_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Degree_combo_box;
    private javax.swing.JTable Student_table;
    private javax.swing.JTextField Studentnumber_field;
    private javax.swing.JButton add_student_button;
    private javax.swing.JButton get_student_details_button;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lecturer_modules_field;
    private javax.swing.JTextField lecturer_name_field;
    private javax.swing.JTextField lecturer_surname_field;
    private javax.swing.JTextField new_credits_field;
    private javax.swing.JTextField new_student_name_field;
    private javax.swing.JTextField new_student_number_field;
    private javax.swing.JTextField new_student_surname_field;
    private javax.swing.JButton remove_student_button;
    private javax.swing.JTextField remove_student_number_field;
    private javax.swing.JComboBox<String> sos_combo_box;
    private javax.swing.JTable student_curriculum_table;
    private javax.swing.JTextField student_degree_field;
    private javax.swing.JTextField student_name_field;
    private javax.swing.JTextField student_risk_field;
    private javax.swing.JTextField student_risk_field1;
    private javax.swing.JTextField student_surname_field;
    private javax.swing.JTextField students_credits_field;
    private javax.swing.JComboBox<String> term_condition_combo_box;
    private javax.swing.JButton view_lecturer_button;
    private javax.swing.JTextField view_lecturer_field;
    private javax.swing.JComboBox<String> years_registered_combo_box;
    private javax.swing.JComboBox<String> yos_combo_box;
    // End of variables declaration//GEN-END:variables
}
