/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mypackage;
import main.main;
import classes.Mysqlconnection;
import java.awt.TrayIcon;
import java.awt.TrayIcon.MessageType;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import classes.User;
import Mypackage.StudentHomeForm;




public class LoginForm extends javax.swing.JFrame {
    Mysqlconnection connect;
    User currentuser;

    public LoginForm() {
        this.connect = new Mysqlconnection();
        this.currentuser=new User();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        input_id_num = new javax.swing.JTextField();
        usertype = new javax.swing.JComboBox<>();
        signin_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        input_pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("ID Number");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 200, 61, 16);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 250, 67, 16);

        input_id_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_id_numActionPerformed(evt);
            }
        });
        getContentPane().add(input_id_num);
        input_id_num.setBounds(230, 200, 209, 22);

        usertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Lecturer", "Administrator" }));
        usertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertypeActionPerformed(evt);
            }
        });
        getContentPane().add(usertype);
        usertype.setBounds(240, 140, 148, 22);

        signin_button.setText("Sign in");
        signin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(signin_button);
        signin_button.setBounds(270, 330, 71, 25);

        exit_button.setText("Exit");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(exit_button);
        exit_button.setBounds(280, 380, 53, 25);
        getContentPane().add(input_pass);
        input_pass.setBounds(230, 250, 209, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/ukznlog2.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 10, 350, 120);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 204, 153));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 450);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void input_id_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_id_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_id_numActionPerformed

    private void usertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertypeActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(this, "Are you sure that you want to exit?", "Confirmation", JOptionPane.YES_NO_OPTION)==0){  //confirm that the user wants to exit the application
        System.exit(0);
         }
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void signin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_buttonActionPerformed
        String usertype=this.usertype.getSelectedItem().toString();     //assign user' details to an object
        String id=this.input_id_num.getText();
        String pass=this.input_pass.getText();
        if(input_id_num.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your identification credentials.", "No Input", JOptionPane.ERROR_MESSAGE);//display an error message for empty login input    
        }
        else{
        try {
 
            if(connect.checkuserdb(usertype, "id", id)){
                if(connect.checkuserdb(usertype, "password", pass)){
                currentuser.setUserID(id);
                currentuser.setAccess_Type(usertype);
                    if(usertype=="Student"){
                        Mypackage.StudentHomeForm nextframe=new StudentHomeForm(currentuser.getUserID(), currentuser.getAccess_Type()); //create a new Srudent frame if the user is a login
                        nextframe.setVisible(true);
                        this.dispose();
                    }
                    else if(usertype=="Lecturer"){
                        Mypackage.LectrurerForm nextframe=new LectrurerForm(currentuser.getUserID(), currentuser.getAccess_Type());     //create a new Lecturer frame if the user is a login
                        nextframe.setVisible(true);
                        this.dispose();
                    }
                    else if(usertype=="Administrator"){
                        Mypackage.AdministratorForm nextframe=new AdministratorForm(currentuser.getUserID(), currentuser.getAccess_Type());//create a new Admin frame if the user is a login
                        nextframe.setVisible(true);
                        this.dispose();
                    }
                }
                else{
                JOptionPane.showMessageDialog(this, "The passowrd entered is incorrect.", "Invalid Password", JOptionPane.ERROR_MESSAGE);   //display an error message for wrong password login input 
                }
                    
            }
            else{
                JOptionPane.showMessageDialog(this, "You're not on the system. Please ensure that the id entered is correct", "Invalid ID", JOptionPane.INFORMATION_MESSAGE);   //display an error message for invalid login input 
            }
            
            
        } catch (Exception ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
    }//GEN-LAST:event_signin_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit_button;
    private javax.swing.JTextField input_id_num;
    private javax.swing.JPasswordField input_pass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton signin_button;
    private javax.swing.JComboBox<String> usertype;
    // End of variables declaration//GEN-END:variables
}
