/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mypackage;
import classes.Curriculum;
import classes.User;
import classes.Mysqlconnection;
import java.awt.TrayIcon;
import java.awt.TrayIcon.MessageType;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import classes.User;
import com.mysql.cj.MysqlConnection;
import javax.swing.table.DefaultTableModel;
public class StudentHomeForm extends javax.swing.JFrame {
    User currentUser;
    Mysqlconnection connect;
    Curriculum student_Curriculum;
    boolean added_to_db;

    /**
     * Creates new form StudentHomeForm
     */
    public StudentHomeForm() {
        currentUser=new User();
        this.connect = new Mysqlconnection();
        added_to_db=false;
        initComponents();
    }
    public StudentHomeForm(String userid, String accesstype) {
        this.connect = new Mysqlconnection();       //create a connection object and intialize
        currentUser=new User();
        currentUser.setUserID(userid);
        currentUser.setAccess_Type(accesstype);
        added_to_db=false;
        initComponents();
          String term_condition="";
          String credits="";
        try {
            String yos=connect.getspecificdata(currentUser.getAccess_Type(), "id", currentUser.getUserID(), "Year of Study");       //set the year of study
            int yos_int=Integer.parseInt(yos);
            String sos=connect.getspecificdata(currentUser.getAccess_Type(), "id", currentUser.getUserID(), "Semester of Study");   //set the semester of study
            int sos_int=Integer.parseInt(sos);
            String degree=connect.getspecificdata(currentUser.getAccess_Type(), "id", currentUser.getUserID(), "Degree");           //set the degree of User
            this.student_Curriculum=new Curriculum(degree, currentUser.getUserID(),yos_int, sos_int);
            term_condition = connect.getspecificdata(currentUser.getAccess_Type(), "id", currentUser.getUserID(), "Term Condition");
            connect.setuptable(past_reults_table, "modules.`students past`", "Module,Mark,`Semester taken`,`Year taken`,Rating", "`Student Number`", currentUser.getUserID());
            if(connect.checkuserdb("modules.`current curriculum`", "id" , currentUser.getUserID())){
                connect.setuptable(current_curriculum_table, "modules.`current curriculum`", "`Module`,Credits", "id", currentUser.getUserID());    //set up the current curriculum table
            }
            connect.setup2vartable(standard_curriculum_table, "modules.`"+degree+"`", "`Module code`, `Module name`,Credits, Pre_requisites, Co_requisites","Year",yos,"Semster",sos);      //set up standard curriculum table
            credits=connect.getspecificdata(currentUser.getAccess_Type(), "id", currentUser.getUserID(), "Credits");
        } 
        catch (Exception ex) {
            Logger.getLogger(StudentHomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        termcondition_textbox.setText(term_condition);
        total_credits_textbox.setText(credits);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        termcondition_textbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        past_reults_table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        total_credits_textbox = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        add_curricululm_button = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        standard_curriculum_table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        current_curriculum_table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnGenerateCurriculum = new javax.swing.JButton();
        Curriculum_credits_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        search_degree_combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        view_year_combo = new javax.swing.JComboBox<>();
        view_semester_combo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        general_modules_tables = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        student_logout_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jTabbedPane3.setBackground(new java.awt.Color(0, 255, 51));

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Term Condition");

        termcondition_textbox.setEditable(false);

        past_reults_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Module", "Mark ", "Semester taken", "Year taken", "Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        past_reults_table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(past_reults_table);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Past Results");

        jLabel4.setText("Total Credits Acheived");

        total_credits_textbox.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_credits_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(termcondition_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(termcondition_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_credits_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Student Home", jPanel1);

        jPanel3.setBackground(new java.awt.Color(51, 255, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        add_curricululm_button.setText("Add Curriculum");
        add_curricululm_button.setBorder(null);
        add_curricululm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_curricululm_buttonActionPerformed(evt);
            }
        });

        standard_curriculum_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Module code", "Module name", "Credits ", "Pre-requisites", "Co-requisites"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        standard_curriculum_table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(standard_curriculum_table);
        if (standard_curriculum_table.getColumnModel().getColumnCount() > 0) {
            standard_curriculum_table.getColumnModel().getColumn(0).setResizable(false);
            standard_curriculum_table.getColumnModel().getColumn(1).setResizable(false);
            standard_curriculum_table.getColumnModel().getColumn(2).setResizable(false);
            standard_curriculum_table.getColumnModel().getColumn(3).setResizable(false);
            standard_curriculum_table.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Current Curriculum");

        current_curriculum_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Module code", "Credits "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        current_curriculum_table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane6.setViewportView(current_curriculum_table);
        if (current_curriculum_table.getColumnModel().getColumnCount() > 0) {
            current_curriculum_table.getColumnModel().getColumn(0).setResizable(false);
            current_curriculum_table.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Standard Curriculum for Semester");

        btnGenerateCurriculum.setText("Generate Curriculum");
        btnGenerateCurriculum.setBorder(null);
        btnGenerateCurriculum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateCurriculumActionPerformed(evt);
            }
        });

        Curriculum_credits_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Curriculum_credits_fieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Credits of current curiculum");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnGenerateCurriculum)
                            .addGap(18, 18, 18)
                            .addComponent(add_curricululm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(Curriculum_credits_field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Curriculum_credits_field, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(btnGenerateCurriculum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_curricululm_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("View Curriculum", jPanel3);

        jPanel2.setBackground(new java.awt.Color(153, 255, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Degree");

        search_degree_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agricultural Engineering", "Chemical Engineering", "Civil Engineering", "Computer Engineering", "Electrical Engineering", "Electronic Engineering", "Mechanical Engineering" }));
        search_degree_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_degree_comboActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Year");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Semester");

        view_year_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "1", "2", "3", "4" }));
        view_year_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_year_comboActionPerformed(evt);
            }
        });

        view_semester_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "1", "2" }));
        view_semester_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_semester_comboActionPerformed(evt);
            }
        });

        general_modules_tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Module code", "Module name", "Year", "Semester", "Credits", "Pre-requisites", "Co-requisites"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        general_modules_tables.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(general_modules_tables);

        jButton1.setText("Get Modules");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addGap(628, 628, 628))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(344, 344, 344))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(284, 284, 284)))
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(135, 135, 135)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(search_degree_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(view_semester_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(view_year_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(search_degree_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(view_year_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(view_semester_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("View Modules", jPanel2);

        student_logout_button.setText("Logout");
        student_logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(student_logout_button)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(student_logout_button)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void student_logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_logout_buttonActionPerformed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(this, "Are you sure that you want to logout?", "Confirmation", JOptionPane.YES_NO_OPTION)==0){        //display confirmation dialog before logging out
            new LoginForm().setVisible(true);
            this.dispose();
         }
    }//GEN-LAST:event_student_logout_buttonActionPerformed

    private void search_degree_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_degree_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_degree_comboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        String view_degree= search_degree_combo.getSelectedItem().toString();
        String view_year=view_year_combo.getSelectedItem().toString();
        String view_semester=view_semester_combo.getSelectedItem().toString();
        if(view_year.equals("ALL")){
            if(view_semester.equals("ALL")){
                connect.setupfulltable(general_modules_tables, "modules.`"+view_degree+"`", "`Module code`, `Module name`, Year, Semster, Credits, Pre_requisites, Co_requisites");
            }

            else{
                connect.setuptable(general_modules_tables, "modules.`"+view_degree+"`", "`Module code`, `Module name`, Year, Semster, Credits, Pre_requisites, Co_requisites","Semster",view_semester);
            
            }
        }
        else{
            if(view_semester.equals("ALL")){
            connect.setuptable(general_modules_tables, "modules.`"+view_degree+"`", "`Module code`, `Module name`, Year, Semster, Credits, Pre_requisites, Co_requisites","Year",view_year);
            }
            else{
            connect.setup2vartable(general_modules_tables, "modules.`"+view_degree+"`", "`Module code`, `Module name`, Year, Semster, Credits, Pre_requisites, Co_requisites","Year",view_year,"Semster",view_semester);
            }   
            }
            }catch (Exception ex) {
                Logger.getLogger(StudentHomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void view_semester_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_semester_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_semester_comboActionPerformed

    private void add_curricululm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_curricululm_buttonActionPerformed
        if(added_to_db==false){
        if(JOptionPane.showConfirmDialog(this, "Are you sure that you want to add this curriculum?", "Confirmation", JOptionPane.YES_NO_OPTION)==0){    //confirm if the user wants to add the generated curriculum
        for(int count=0;count<10 && student_Curriculum.getModulesTaken(count)!=null;count++){       //get all the inputs from the table
            String idvalue=currentUser.getUserID();
            idvalue=idvalue.concat("_");
            idvalue=idvalue.concat(student_Curriculum.getModulesTaken(count));
            String student_num=currentUser.getUserID();
            String module=student_Curriculum.getModulesTaken(count);
            String year_taken=String.valueOf(student_Curriculum.getYear());
            String semester_taken=String.valueOf(student_Curriculum.getSemester());
            String Credits="0";
            String query_values="0";
            try {
                Credits=connect.getspecificdata("modules.`"+student_Curriculum.getDegree()+"`", "`Module code`",student_Curriculum.getModulesTaken(count) , "Credits");     //get the credits of each value in the generated curriculum
            } catch (Exception ex) {
                Logger.getLogger(StudentHomeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            query_values="'"+idvalue+"','"+student_num+"','"+module+"','"+year_taken+"','"+semester_taken+"','"+Credits+"'";
            try {
                connect.addtodb("modules.`current curriculum`", query_values);                      //add modules to the current curriculum database table
            } catch (Exception ex) {
                Logger.getLogger(StudentHomeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                    
            }
            JOptionPane.showMessageDialog(this, "The generated curriculum has been added to the system", "Curriculum added", JOptionPane.INFORMATION_MESSAGE);
            added_to_db=true;
        }
        }
        else JOptionPane.showMessageDialog(this, "The generated curriculum has already been added to the system", "Curriculum added", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_add_curricululm_buttonActionPerformed

    private void btnGenerateCurriculumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateCurriculumActionPerformed
        try {
            if(connect.checkuserdb("modules.`current curriculum`", "id" , currentUser.getUserID())){
                JOptionPane.showMessageDialog(this, "A curriculum has already been generated and assigned.", "Curriculum already established",JOptionPane.INFORMATION_MESSAGE);     //display a message if a curriculum has already been generated
            }
            else if(student_Curriculum.getModulesTaken(0)!=null){
                 JOptionPane.showMessageDialog(this, "A curriculum has already been generated.", "Curriculum already generated",JOptionPane.INFORMATION_MESSAGE);       
            }
            else{
                student_Curriculum.generatecurriculum();        //if a curriculum has not been generated yet, generate it
                for(int count=0;count<10;count++){
                    System.out.print(student_Curriculum.getModulesTaken(count));
                }
                DefaultTableModel model= (DefaultTableModel) current_curriculum_table.getModel();
                for(int count=0;count<10 && student_Curriculum.getModulesTaken(count)!=null;count++){
                    model.insertRow(model.getRowCount(), new Object[]{student_Curriculum.getModulesTaken(count),Integer.parseInt(connect.getspecificdata("modules.`"+student_Curriculum.getDegree()+"`", "`Module code`",student_Curriculum.getModulesTaken(count) , "Credits"))});
                }
                Curriculum_credits_field.setText(String.valueOf(student_Curriculum.getTotalCredits()));
            }
        } catch (Exception ex) {
            Logger.getLogger(StudentHomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerateCurriculumActionPerformed

    private void Curriculum_credits_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Curriculum_credits_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Curriculum_credits_fieldActionPerformed

    private void view_year_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_year_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_year_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentHomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Curriculum_credits_field;
    private javax.swing.JButton add_curricululm_button;
    private javax.swing.JButton btnGenerateCurriculum;
    private javax.swing.JTable current_curriculum_table;
    private javax.swing.JTable general_modules_tables;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable past_reults_table;
    private javax.swing.JComboBox<String> search_degree_combo;
    private javax.swing.JTable standard_curriculum_table;
    private javax.swing.JButton student_logout_button;
    private javax.swing.JTextField termcondition_textbox;
    private javax.swing.JTextField total_credits_textbox;
    private javax.swing.JComboBox<String> view_semester_combo;
    private javax.swing.JComboBox<String> view_year_combo;
    // End of variables declaration//GEN-END:variables
}
